In [42]:
from sklearn import datasets
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from IPython.display import display

In [7]:
iris = datasets.load_iris()
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [15]:
print('data shape :',iris.data.shape)
print('iris target :',iris.target_names)
print('iris features :',iris.feature_names)

X = iris.data # 데이터(특성,변수)
print('type x:', type(X)) # 타입을 확인하는 과정을 중요하다 array인지 list 인지
print(X[:5])
y = iris.target # 분류클래스 (레이블 종속 y)
print('type y: ', type(y))
print(y[:5])

data shape : (150, 4)
iris target : ['setosa' 'versicolor' 'virginica']
iris features : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
type x: <class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
type y:  <class 'numpy.ndarray'>
[0 0 0 0 0]


In [16]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
scaler = StandardScaler()
scaler.fit(x_train,y_train)
x_train_scale  = scaler.transform(x_train)
x_test_scale = scaler.transform(x_test)
print(x_train_scale)
print(x_test_scale)
# scale을 해주는 이유 : overfitting 방지, 연산속도 상승 등등.

[[-0.31904483 -0.39416363 -0.10125726  0.10682395]
 [ 1.00114067  0.48994171  1.06923955  1.64508885]
 [-0.31904483 -0.1731373   0.17743245  0.10682395]
 [-0.31904483 -0.61518997  0.623336    1.00414514]
 [ 0.52107322  0.71096805  1.01350161  1.51690011]
 [ 0.04100576  0.26891538  0.56759806  0.74776766]
 [ 0.76110694 -0.1731373   1.1249775   1.26052263]
 [-0.43906169 -1.49929532 -0.04551932 -0.27774227]
 [-1.27917974  0.71096805 -1.04880231 -1.30325221]
 [-1.27917974 -0.1731373  -1.32749203 -1.17506346]
 [-1.03914601  0.93199439 -1.21601614 -0.79049724]
 [ 1.2411744   0.26891538  1.06923955  1.38871137]
 [-0.19902797  1.5950734  -1.16027819 -1.17506346]
 [ 0.64109008 -0.61518997  1.01350161  1.26052263]
 [ 1.60122499 -0.1731373   1.1249775   0.49139018]
 [ 0.64109008  0.04788904  0.95776367  0.74776766]
 [-0.43906169 -1.27826898  0.12169451  0.10682395]
 [-0.31904483 -0.83621631  0.2331704   0.10682395]
 [-1.3991966   0.26891538 -1.38322997 -1.30325221]
 [-1.3991966   0.26891538 -1.21

In [17]:
# 머신러닝 모델 선택.
gnb = GaussianNB()
gnb.fit(x_train_scale,y_train) # 모델 학습
y_pred = gnb.predict(x_test_scale) # 예측
display(confusion_matrix(y_test,y_pred)) # 분류모델의 성능평가. 오차행렬
# y(specise 의 클래스가 3가지 이므로 3x3 이 나온것.)
print(classification_report(y_test,y_pred))

array([[ 9,  0,  0],
       [ 0, 14,  1],
       [ 0,  0,  6]], dtype=int64)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.93      0.97        15
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.98      0.96        30
weighted avg       0.97      0.97      0.97        30



In [39]:
# 와인 데이터 셋을 이용하여 나이브즈 
wine = datasets.load_wine()
print("Features: ", wine.feature_names)
print("Labels: ", wine.target_names)

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']


In [40]:
X = wine.data
y = wine.target
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)

In [41]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)
print("Accuracy: ", metrics.accuracy_score(y_test,y_pred))

Accuracy:  1.0


In [45]:
# cross validation 를 이용한 성능평가 (정확도) 96프로 정도를 설명할 있다.
# x변수를 이런~이런걸 사용해서 y를설명하는데 설명력 
scores = cross_val_score(gnb,X,y,cv=5,scoring='accuracy') 
print(scores)
print(scores.mean())

[0.94444444 0.97222222 0.97222222 0.94285714 1.        ]
0.9663492063492063
